import streamlit as st
from ui.helpers import inject_css, load_report, ROOT

def render():
    inject_css()
    st.title("📊 Full Benchmark Report")
    st.caption("Complete Sakshi audit report generated by `scripts/report.py`")

    report = load_report()
    st.markdown(report)

    st.divider()
    st.download_button("⬇️ Download Raw Markdown", data=report,
                       file_name="sakshi_benchmark_report.md", mime="text/markdown")
