"""Generate one local development Ed25519 key for the durable Atlas demo.

The key is written to a git-ignored file and never printed.  It is useful for
demonstrating persistence across a restart, but it is not a production KMS/HSM
key.  The script refuses to overwrite an existing file.
"""
from __future__ import annotations

import argparse
import base64
import os
from datetime import datetime, timezone
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat


ROOT = Path(__file__).resolve().parent.parent


def _b64(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).decode("ascii").rstrip("=")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=".atlas-evidence.env", help="git-ignored output path relative to the repo")
    args = parser.parse_args()
    out = ROOT / args.out
    if out.exists():
        raise SystemExit(f"Refusing to overwrite existing local evidence key: {out}")
    private = Ed25519PrivateKey.generate().private_bytes(Encoding.Raw, PrivateFormat.Raw, NoEncryption())
    key_id = "atlas-local-" + datetime.now(timezone.utc).strftime("%Y%m%d")
    content = (
        "# Local development key generated by scripts/generate_evidence_key.py. Never commit.\n"
        f"SAKSHI_EVIDENCE_PRIVATE_KEY_B64={_b64(private)}\n"
        f"SAKSHI_EVIDENCE_KEY_ID={key_id}\n"
        "ATLAS_EVIDENCE_DB=data/atlas_evidence.db\n"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"Created git-ignored local development evidence key at {out.name}. Restart the server to enable durable mode.")


if __name__ == "__main__":
    main()
